[project]
name = "repl-nix-radioplayerapp"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "numpy>=2.1.3",
    "python-vlc>=3.0.21203",
    "requests>=2.32.3",
    "sounddevice>=0.5.1",
    "wavio>=0.0.9",
]
